name: Docker CD

on:
  push:
  workflow_dispatch:

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    name: Docker build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: qrpyora-blur # this image-name is changed for the demo
